### ISSUE TITLE
Ghana field testing Issues

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1040]
Due to time, I decided to add some issues together as list below, I will log them as independent issues latter:

* Sample: 
  Shipment date is allowed to be in the future but reception date is not allowed. This create errors as a future shipment date prevent the user to report the correct reception date. In addition, the lab cannot edit the shipment date.  We should prevent all dates (shipment, reception, date sample was collected from being in the future, and reception date should be the same date or after shipment date). eg Correcting a wrong date of shipment on app: The initial date of sample collection was 03/04/19 (current calendar date) and date of shipment was 04/04/19.  The app blocks the user from correcting the dates. #1139
* Under hospitalization:
  - [x] Accommodation has no "Unknown option", needs to be added #1063
  - [ ] ~~Accommodation should appear as option only when admission is "Yes"~~
* Contact visits:
  - [x] In registering a new visit, all symptom icons appear red as if there is an error. They should stay blue except  when the user try to save without checking any option for the symptoms #1064
  - [x] Date of symptom onset is visible and can be edited when all symptom are set to NO, this should only appear when at least one symptom is set to yes for a contact person or a case person. #1064
  - ~~Complications should not appear as option during a visit to a contact or case creation. This should only appear under clinical course.  ~~
* Case Information: Can we auto-fill the sample code with the epid number #1136 
* The hospital Informant user-right is not able to edit outcome. One person in Ghana asked for it. 
 Should this be allowed for informant? -> They are surveillance officers, so it's not a problem
* "Case listing" on mobile app: 
  - [x] Create a search option on the mobile app to search cases by names, disease, etc especially for the case listing view. This is however of low priority for now. #1078
  - [x] The synchronization icon on app still displays after synchronization is successful, this should be checked out.
* [x] Unconfirmed contact appears "orange" rather than "grey", We should use the same colours as in case classifications. #1070

**Comment by MartinWahnschaffeSymeda** [comment]
* Also confirmed contact should be red

**Comment by MartinWahnschaffeSymeda** [comment]
Created issues for all points
