### ISSUE TITLE
Refinement of Processing Lab Messages

### ISSUE THREAD

**Issue by KristinaBorch** [hzi-braunschweig/SORMAS-Project#10754]
### Situation Description & Motivation

With the implementation of samples being attached to persons, it should be possible while processing messages to add them to a person instead of a case/contact/Event participant (EP). Therefore, the user needs to be able to decide whether a new person should be created or an existing person is chosen both with or without out a case/contact/EP. Therefore, the current Lab Message Process needs to be refined. Please note, before implementation it should be possible to add samples to the person view without another entity https://github.com/hzi-braunschweig/SORMAS-Project/issues/10714.

### High-Level Explanation

For the above explained purpose the workflow of processing lab messages should be refined. When processing a message the pick or create person window appears. For this sup-options are needed which allows the user to decide if a new person should be created only or if a case, contact or event participant should be created. These three options should a available as sub options to the option create new person. Next tot hat, when choosing an existing or matching person there should be another option available which allows to create a new sample without choosing a case, contact or event participant. After deciding to create a new person only, a new window to create person is needed, which should be similar structured as the create case window. 

### Tasks

- [ ] https://github.com/hzi-braunschweig/SORMAS-Project/issues/10759
- [ ] https://github.com/hzi-braunschweig/SORMAS-Project/issues/10757
- [ ] https://github.com/hzi-braunschweig/SORMAS-Project/issues/10756

**Comment by KristinaBorch** [comment]
As initial issue was changed, this epic is not relevant anymore.
