### ISSUE TITLE
Create a github project with the SORMAS roadmap (next 3 quarters)

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1127]
- [x] create the project
- [x] assign existing epic issues
- [x] create misisng epic issues
