### ISSUE TITLE
[DEMIS2SORMAS] Extension of the Mapping for lab messages and physician reports

### ISSUE THREAD

**Issue by markusmann-vg** [hzi-braunschweig/SORMAS-Project#11447]
### Situation Description & Motivation
To simplify the processing of lab messages and physician reports we are extending the SORMAS2DEMIS Mapping.

#### Use cases
- TestedDiseaseVariant
- ReportDate
- Date of result
- LabName
- Reinfection

### Tasks

- [ ] #11449 
- [ ] #11453  
- [ ] #11454 
- [ ] #11456 
- [ ] #11457 

SurvNet
- [ ] https://github.com/hzi-braunschweig/sormas-survnet-interface/issues/352
- [ ] https://github.com/hzi-braunschweig/sormas-survnet-interface/issues/353
- [ ] https://github.com/hzi-braunschweig/sormas-survnet-interface/issues/354

Demis-Adapter ([epic](https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/79))
- [ ] https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/80
- [ ] https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/81
- [ ] https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/82
- [ ] https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/83

**Comment by markusmann-vg** [comment]
Will be covered by

https://github.com/hzi-braunschweig/SORMAS-Project/issues/9504
