### ISSUE TITLE
Payara 6 and Jakarta EE 10

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#11530]
### Situation Description & Motivation
Starting in 2023, Payara 6 will be the new community edition, and Payara 5 Community Edition will not get updates anymore. With Payara 6 there will be Jakarta EE 10 used. We need to do a lot of changes to migrate to Payara 6.

https://www.payara.fish/downloads/payara-platform-community-edition/

Benefits of Jakarta 10: https://jakarta.ee/release/10/

* Jakarta Persistence standardizing UUID as Basic Type and extending Query language and Query API
* Jakarta JSON Binding (JSON-B) 3.0
* Jakarta Security 3.0 supporting OpenID Connect
* Spring 6 is also Jakarta 10 complient (does not include EJB) - this may be a good step to either move there or at least allow us a better partly integration of features offered by Spring

### High-Level Explanation

- [ ] #11109
- [ ] Create dedicated issues of all dependencies / migration steps that can be done on their own
- [ ] Update to Payara 6 and Jakarta EE 10

### Tasks

- [ ] #10499 ?
- [ ] #10074
- [ ] Jakarta 10 for cdi-unit
- [ ] #6699
- [ ] ...
