### ISSUE TITLE
Integration SORMAS-Docker and S2S-Testbed into SORMAS-Project

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#11985]
### Situation Description & Motivation
We currently have docker files in SORMAS-Docker, S2S-Testbed and cargoserver in SORMAS-Project all of which setup and deploy sormas servers, but with slightly different main purpose (operations, S2S-testing, local development). S2S-Testbed and cargoserver are rarely used and thus are not well maintained. 

It would be beneficial to combine all of this into one place, so it:

* is easier to maintain, 
* allows building the image from source instead of pulling the release artifact
* which also allows devs to create a docker image out of their current branch

There are a few more things that should be improved:
(originally posted here https://github.com/hzi-braunschweig/SORMAS-Project/issues/11700)

1. Consolidate the payara, Rscript, and sormas build into one file as the intermediates have no value on their own. Chain them or use multistage build if it makes sense. 
2. sormas/setup-server.sh should work on the ZIP obtained by a build stage container
3. sormas/start-server.sh is overly complicated. There is no need to invoke asadmin in the script dynamically based on env variables as configured pre/post-boot.asadmin files can be mounted into the container. Same goes probably for the hundreds of sed lines to template sormas.properties inside the starting container instead of passing a configuration file to the container when it starts. This should significantly reduce the LOC in the repo and avoid the cascading usage of environment variables.

#### Use cases

* Docker images for production systems can be built and published
* Developers can run docker containers based on the current branch
* Developers can run a container for keycloak in combination with a local installation of payara and database or keycloak and payara in containers with local database, or ...
* Easy local setup for S2S
* Easy local setup for additional modules like survnet-converter or demis-adapter

### Tasks

- [ ] Define needed steps to integrate SORMAS-Docker and S2S-Testbed into SORMAS-Project
- [ ] Move SORMAS-Docker files to SORMAS-Project
- [ ] TBD
- [ ] #9580
- [ ] #11700 or at least use GitHub Actions to build and release the docker images to dockerhub
