### ISSUE TITLE
Transmission Chain Visualization [5]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1563]
### Feature Description
Based on the existing prototype the transmission chain visualization needs to be optimized to be usable on production systems. This includes improving the creation and visualization performance, internationalization and improved visualization options.

### Proposed Change
- [x] Pass a list of relevant contacts (ids) to the R script. Thisway the filtering based on disease, user rights and time period can be done in the backend with existing logic. Only use contacts that do have a case reference.
- [ ] Internationalize captions and enum values -> replace when importing the JSON generated by the R script -> #1950
- [ ] Add option to display it as hierarchy --> #1951
- [ ] ~~Use vaadin resource to make the creation & update of the component asnyc~~
- [x] Only display diagram when maximized
- [x] Extend setup script & manual (see #1168)

### HZI
- [x] Don't display ids of persons on the node. Instead for case nodes show the short uuid (first 6 characters). For contact person nodes don't show something for now
- [x] Adjust the colors based on the colors used in the dashboard (confirmed = red, etc.)
- [x] Nodes should not be so flexible (probably also helps to improve performance)
- [x] Add option to display it as hierarchy

**Comment by HolgerReiseVSys** [comment]
The list of contact ids should be handed over to the script as comma separated string in the environment variable CONTACTS.

**Comment by bernardsilenou** [comment]
@MartinWahnschaffeSymeda  will it be the same form as the contact data exported from the front end? see picture attached. If not can you give me a sample by exporting from Martins personal db?
![image](https://user-images.githubusercontent.com/12996724/77553501-29f0bc00-6eb5-11ea-8c25-75634a1fc69c.png)

**Comment by HolgerReiseVSys** [comment]
One issue with the i18n is that the backend knows not of the user language.
It could be forwarded from the ui.

**Comment by HolgerReiseVSys** [comment]
Remaining work has been moved to new tickets #1950 and #1951

**Comment by StefanKock** [comment]
Is here still a review needed or can this ticket be considered done, since it is already released?

**Comment by MartinWahnschaffeSymeda** [comment]
Let's consider it done
