### ISSUE TITLE
Infrastructure import problems related to umlauts

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1583]
### Bug Description
1. Importing ü, ä, ö, etc. does not correctly work (e.g. misspelled in name)
[sormas_import_region_germany.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/4318702/sormas_import_region_germany.txt)
2. Importing a district for a region with a ß in it's name does not work. The logic does an uppercase and this probably behaves differently for Java and JPA/SQL.. 
[sormas_import_district_landkreise.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/4318724/sormas_import_district_landkreise.txt)

### TODO

- [x] Write unit test
- [x] Fix umlaut encoding problems
- [x] Fix ß uppercase problem
- [x] ~Accept import files that come with a BOM~ => using BOM is generally not recommended by Unicode
- [x] Add comments to CaseImporter and InfrastructureImporter to explain what happens

**Comment by MateStrysewskeSym** [comment]
I've created some unit tests. Unfortunately, H2 seems to behave differently than PostgreSQL which is why all tests are passing right now.

We could solve the ß <-> SS problem by using toLowerCase instead of toUpperCase and maybe adding two different areas of name matching (1. match for exact name without manipulating the string, 2. use toLowerCase).
