### ISSUE TITLE
Requirements from Debug Form from the Workshop 2017

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Project#181]
@MartinWahnschaffeSymeda Please find attached the debug forms extracted from the form database containing the responses from the workshop.
[Debug Forms Workshop.xlsx](https://github.com/hzi-braunschweig/SORMAS-Open/files/915874/Debug.Forms.Workshop.xlsx)

**Comment by MartinWahnschaffeSymeda** [comment]
Extracted from the list:

- [ ] linking epid calendar in week number for case analysis   
- [ ] Auto system setting after symptoms, no symptom even when there are symptoms
- [ ] "shipment" should be changed to "sample sent". "Date sample received" should be moved upward immediately after ticking sample sent
- [ ] If the the specimen is not adequate, the page button on the  patient information page should be inactive, An alert system (Via phone/Email should always accompany all request for laboratory diagnosis, 
- [ ] On the lab Section The need for Realignment of Date Received and Put the Date Botton just like Date of Shipment.
- [ ] New result button and Adapt the Nigerian System of reporting
- [ ] FOR THE LAB SECTION LET US THINK ABOUT THE INTERNAL AND EXTERNAL QA ISSUES AND BIO-DEPOSITORY FOR FUTURE. LINKAGE WITH LAB BASED SURVEILLANCE SYSTEM AND AMR /WHO-NET FOR AMR SURVEILLANCE
- [ ] The flow of the sample collection, shipping and storing can be different from the lab results, the flow can be: Sample collection(type, ...) --> shipping (date and method)--> receiving (date)--> accept/reject --> if Accept (status then proceed to results), if reject add a reason and a procedure like asking for another sample... \n\nReferral is done after accepting if the test is not available at the first lab. The procedure should be the same starting again with shipping .......
- [x] For Avian Influenza, the sample types should be categorized and differentiated for human samples, animal samples and other environmental samples that may be required. This will help effective analysis to separate columns on the table structure for the different samples being referred to.  #178 
- [ ] The address of the contact person should be a required field and should be priority after the relationship to the case is defined. 
- [ ] The information about the investigated and not investigated cases should be summarized to each persona involved to be able to follow up on the reported cases and the tasks needed
- [ ] Define the main ALERTS that should be notified to the supervisors, like new cases for specific disease, thresholds for other disease, tasks that has not been performed
- [ ] Login from a different location or someone else is using the same authentication, should notify the user by SMS or email
- [ ] when confirming a disease by lab, the status should be changed accordingly to probable or confirmed. The approval of the higher authority to announce the case can be set separately
- [ ] This persona should available for the hospitals where there is a lab available the  samples can be tested inside the hospital lab
- [ ] The date should not be mandatory as the informant may have the sympotoms but not the dates for it.
- [x] The first symptom, can be a drop down from the selected symptoms to avoid mistyping #175 
- [ ] Mobile interface is available, better to give the option to use the web interface in a comfortable way (not the same way as the mobile interface)
- [x] Animal Contact Environment #173 
- [x] 1. Inability to clear out checked in symptoms (Yes, No, unknown). Once checked cannot be unchecked for wrong entries during reporting.\n\n2. Wrong label for "date of disease onset" #175 
- [ ] Feedback of investigations done is included on the informant platform.This is not needed for the informant but result of investigation can be shared since the case is from her health facilities in line with what is obtainable presently. Results of investigations are sent back to Health facilities 
- [ ] not adding epid number in week to case reporting

**Comment by MartinWahnschaffeSymeda** [comment]
@bernardsilenou @hzi-braunschweig  Please go through this when you find some time and see what is still relevant.
