### ISSUE TITLE
Add area infrastructure level above region [3]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#1983]
### Situation Description
SORMAS currently uses region, district and community, with region and district being mandatory fields for the core entities like cases and contacts.

### Feature Description
In addition to that APMS needs a forth level. ~~Either a "cluster" level below community that will be used for the campaigns or~~ an "area" level to be used for the "regions" (East, etc.) above the SORMAS region. (standard caption should be "zone")

Suggestion is to go with the "area" option, because the province (region in SORMAS) and district levels in AFG are most important (as they are in SORMAS) and the community level is a good fit for clusters.

### Implementation steps

- [x] Add new area infrastructure type. See regions for reference
- [x] Importing, exporting, archiving
- [x] A region can optionally be associated to an area. This should also be part of the import for the region
- [x] Add feature configuration for the new feature (consider import/export templates)

**Comment by MartinWahnschaffeSymeda** [comment]
Based on this, I'm not sure if wer should really map the region in AF to the region in SORMAS.
This needs to be discussed again.
