### ISSUE TITLE
Connection closed / broken pipe on sync

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#2281]
### Bug Description
During sync (mostly initial) the connection is closed and sync cancelled.

This happens in Fiji, a system with a lot of contacts & visits (@fhauptmann approx numbers would be good) and low bandwidth.

Based on the logs (see below) it seems likely that the requests take too long. The app currently has a read-timeout of 60 seconds.

### Todo

- [x] Increase read timeout in app to 4 minutes
- [x] Increase write timeout in app to 1 minute
- [x] Check performance of /sormas-rest/contacts/all/0 -> may result in a separate issue
- [x] CHeck performance of /sormas-rest/visits/query -> may result in a separate issue

### System Details
* SORMAS version: 1.41.1

### Additional Information

```
[2020-06-08T08:37:45.073+1200] [Payara 5.192] [INFO] [] [] [tid: _ThreadID=35 _ThreadName=http-thread-pool::http-listener-1(4)] [timeMillis: 1591562265073] [levelValue: 800] [[
  D083745.073|     > requestUri = /sormas-rest/contacts/all/0 (de.symeda.sormas.rest.logging.RequestResponseLogger.java:68)
]]

[2020-06-08T08:39:33.460+1200] [Payara 5.192] [SEVERE] [] [org.glassfish.jersey.server.ServerRuntime$Responder] [tid: _ThreadID=35 _ThreadName=http-thread-pool::http-listener-1(4)] [timeMillis: 1591562373460] [levelValue: 1000] [[
  An I/O error has occurred while writing a response message entity to the container output stream.
org.glassfish.jersey.server.internal.process.MappableException: java.io.IOException: Connection is closed
```

```
[2020-06-08T08:09:14.153+1200] [Payara 5.192] [INFO] [] [] [tid: _ThreadID=9372 _ThreadName=http-thread-pool::http-listener-1(22)] [timeMillis: 1591560554153] [levelValue: 800] [[
  D080914.152|     > requestUri = /sormas-rest/visits/query (de.symeda.sormas.rest.logging.RequestResponseLogger.java:68)
]]

[2020-06-08T08:10:43.226+1200] [Payara 5.192] [SEVERE] [] [org.glassfish.jersey.server.ServerRuntime$Responder] [tid: _ThreadID=9372 _ThreadName=http-thread-pool::http-listener-1(22)] [timeMillis: 1591560643226] [levelValue: 1000] [[
  An I/O error has occurred while writing a response message entity to the container output stream.
org.glassfish.jersey.server.internal.process.MappableException: java.io.IOException: Connection is closed
```

```
[2020-06-08T07:05:08.743+1200] [Payara 5.192] [INFO] [] [] [tid: _ThreadID=271 _ThreadName=http-thread-pool::http-listener-1(7)] [timeMillis: 1591556708743] [levelValue: 800] [[
  D070508.743|     > requestUri = /sormas-rest/contacts/all/0 (de.symeda.sormas.rest.logging.RequestResponseLogger.java:68)
]]

[2020-06-08T07:07:19.323+1200] [Payara 5.192] [SEVERE] [] [org.glassfish.jersey.server.ServerRuntime$Responder] [tid: _ThreadID=271 _ThreadName=http-thread-pool::http-listener-1(7)] [timeMillis: 1591556839323] [levelValue: 1000] [[
  An I/O error has occurred while writing a response message entity to the container output stream.
org.glassfish.jersey.server.internal.process.MappableException: java.io.IOException: Connection is closed
```

```
[2020-06-08T18:28:29.002+1200] [Payara 5.192] [INFO] [] [] [tid: _ThreadID=274 _ThreadName=http-thread-pool::http-listener-1(10)] [timeMillis: 1591597709002] [levelValue: 800] [[
  D182829.001|     > requestUri = /sormas-rest/visits/query (de.symeda.sormas.rest.logging.RequestResponseLogger.java:68)
]]

[2020-06-08T18:31:10.967+1200] [Payara 5.192] [SEVERE] [] [org.glassfish.jersey.server.ServerRuntime$Responder] [tid: _ThreadID=274 _ThreadName=http-thread-pool::http-listener-1(10)] [timeMillis: 1591597870967] [levelValue: 1000] [[
  An I/O error has occurred while writing a response message entity to the container output stream.
org.glassfish.jersey.server.internal.process.MappableException: java.io.IOException: Connection is closed
```
