### ISSUE TITLE
Health Facility and Laboratory Administration (POS 9) [5]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#232]
See https://app.moqups.com/symeda/3NUENEwuOE/view/page/a39f20492

- [x] add create, edit, view and archive user rights
- [x] add "Infrastructure" view and menu entry. View should have url "facilities" (sub menu is not needed now). Caption is facilities (not health facility)
- [x] add facility grid to view
- [x] text filter by name and city
- [x] filters for region and district (not community)
- [x] header-filters "Health facilities" and "Laboratories" -> update mockups
- [x] build create and edit form (popup)
- [x] facilities get no type, laboratories get the "LABORATORY" type
- [x] add a saveFacility method to the Controller that calls a save method in the facade, use ensurePersisted in that method
- [x] make sure that facilities always have region, district and community set (and a name); laboratories only need a region
- [x] "Other facility", "Home or other place" (NO_FACILITY) and "Other Laboratory" should not appear in the list -> do this by filtering out facilities without a region

Import of regional data is possible via csv from the technical backend. A user interface will be added later (see #436)

- CaseFacadeEjb.saveCase does validation on region, etc - what if community is moved?

**Comment by ChristopherRiedelSymeda** [comment]
tab order of configuration view:
Health Facilities; Laboratories; Outbreaks;

**Comment by MateStrysewskeSym** [comment]
- [ ] give read access to everyone who can also access outbreaks
- [ ] add proper sorting to grids
- [ ] temporarily disable region, district and community in edit layout

**Comment by MateStrysewskeSym** [comment]
- [ ] Make sure that cases are properly transfered when the infrastructure information of a health facility changes

**Comment by MateStrysewskeSym** [comment]
Issue is complete, see #782 for how effects of region, district and community changes are handled.

**Comment by MateStrysewskeSym** [comment]
- [ ] select Configuration tab when in facilities grid

**Comment by MartinWahnschaffeSymeda** [comment]
Things done:

- [x] introduce ROOT_VIEW_NAME for views with sub menu and use it for active menu point selection
- [x] multiselect querries to fill index dtos of facility, district and community to make infrastructure views faster

**Comment by MateStrysewskeSym** [comment]
- [ ] look into OutOfMemoryException when loading facilities

**Comment by MartinWahnschaffeSymeda** [comment]
I have increased the java heap sie to 1024 (-Xmx1024) in the domain.xml config.

- [ ] update glassfish config script
- [x] apply to sormas symeda server
- [ ] apply to sormas HZI server
- [x] apply to sormas Nigeria server

**Comment by MartinWahnschaffeSymeda** [comment]
I have increased the java heap sie to 1024 (-Xmx1024) in the domain.xml config.

- [ ] update glassfish config script
- [x] apply to sormas symeda server
- [ ] apply to sormas HZI server
- [x] apply to sormas Nigeria server

@MateStrysewskeSym The release should be ok this way.
