### ISSUE TITLE
[tracking issue] Complete Java 11 Transition

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#2617]
For now, we are in a transition period to Java 11 and don't allow language features above Java 8.

- [x] Wait some reasonable time
- [x] Drop support for older JDK [releases](https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#release) -> #6699 
- [x] Update CI
- [x] Vaadin Designer 8 is not compatible with IntelliJ running with Java 11 (Vaadin 8 related: #1406 and #1014)
