### ISSUE TITLE
UI-Testing Automation Overview

### ISSUE THREAD

**Issue by chThie** [hzi-braunschweig/SORMAS-Project#4034]
This issue is used to track which tested features are already covered in [sormas-e2e-ui-tests](https://github.com/hzi-braunschweig/SORMAS-Project/tree/development/sormas-e2e-ui-tests).
The goal is to automate as many of the test cases as possible to avoid time-consuming manual testing (especially for well-established features).
As previously discussed, feel free to mark what is already covered (@raghupola-vg) and to add/adjust features to test (@kwa20). The list is based on the manual test protocol and we should probably refine it to be precise in what exactly should be tested.

# Tested Features
## Dashboard
- [ ] Surveillance Dashboard
- [ ] Contacts Dashboard
## Tasks 
- [x]  Create a new task
- [ ]  Bulk editing mode
- [ ]  Basic export
- [ ]  Filter
## Cases
- [x]  Create a new case
### Tab: Case
- [ ]  Confirmation
- [ ]  Case definition category
- [ ]  Investigation status
- [ ]  Course of the disease 
- [ ]  Type of reporting
- [ ]  Origin of case
- [ ]  Quarantine
- [ ]  Medical information (if female)
- [ ]  Responsible surveillance officer
- [ ]  Follow-up status
- [ ]  Reception date
- [ ]  General comment
- [ ]  Archive/Delete
- [ ]  Create a new task
- [ ]  Create a new sample
- [ ]  Link to an event
- [ ]  Create documents
### Tab: Case person
- [ ]  Information of the person
- [ ]  Occupation & Education
- [ ]  Home address
- [ ]  Addresses
- [ ]  Contact information
### Tab: Symptoms
- [ ]  Clinical Measurements
- [ ]  Clinical signs and symptoms
- [ ]  Adoption of visits
### Tab: Epidemiological data
- [ ]  Exposure investigation
- [ ]  Exposure details known
- [ ] Create new exposure
    - [ ]  Exposure dates and description
    - [ ]  Type of activity (details)
        - [ ]  Type of gathering (details)
        - [ ]  Type of habitation (details)
        - [ ]  Type of animal (details)
    - [ ]  Exposure Details
    - [ ]  Contact to source case (entered previously)
    - [ ]  Burial Details
    - [ ]  Animal Contact Details
    - [ ]  Location
- [ ]  Area with high risk of transmission
- [ ]  Countries experiencing larger outbreaks
- [ ]  Contacts with Source Case
- [ ]  Create new contact
### Tab: Therapy
- [ ]  Create new prescription
    - [ ]  Switch on bulk editing 
- [ ]  Create a new treatment
    - [ ]  Switch on bulk editing 
### Tab: Clinical course
- [ ]  Create a new clinical assessment
    - [ ]  Switch on bulk editing 
- [ ]  Preconditions
### Tab: Contacts
- [ ]  Create a new contact
- [ ]  Set a filter
- [ ]  Switch on bulk editing 
- [ ]  Import
- [ ]  Export
### Tab: Follow-up visits/calls
- [ ]  Bulk editing mode
- [ ]  Export
- [ ]  Create a new visit/call
## Case Directory
- [ ]  Detailed
- [ ]  Follow-Up
- [ ]  Filter/Sort
- [ ]  Import (cases, case contacts)
- [ ]  Export (simple/detailed/etc.)
- [ ]  Line listing - create cases
- [ ]  Open existing case
- [ ]  more
## Contacts
- [x]  Create a new contact
### Tab: Contact
- [ ]  Contact classification
- [ ]  Convert contact into case
- [ ]  responsible State/Region
- [ ]  Type of contact (not relevant for international?)
- [ ]  Contact category
- [ ]  Relationship with case
- [ ]  Quarantine
- [ ]  Priority
- [ ]  Per-existing conditions
- [ ]  Immunosupp. Therapy
- [ ]  Nursing activity
- [ ]  Follow-up status
- [ ]  Chose source case/ change case
- [ ]  Create a new task
- [ ]  Create a new sample
### Tab: Contact person
- [ ]  Person- Information
- [ ]  Occupation & Education
- [ ]  Home address
- [ ]  Addresses
- [ ]  Contact information
### Tab: Epidemiological data
- [ ]  Exposure investigation
- [ ]  Exposure details known
- [ ]  Create new exposure
    - [ ]  Exposure dates and description
    - [ ]  Type of activity (details)
        - [ ]  Type of gathering (details)
        - [ ]  Type of habitation (details)
        - [ ]  Type of animal (details)
    - [ ]  Exposure Details
    - [ ]  Contact to source case (entered previously)
    - [ ]  Burial Details
    - [ ]  Animal Contact Details
    - [ ]  Location
- [ ]  Area with high risk of transmission
- [ ]  Countries experiencing larger outbreaks
### Tab: Follow-up visits/calls
- [ ]  Bulk editing mode
- [ ]  Export
- [ ]  Create a new visit/call
## Contacts Directory
- [ ]  Detailed
- [ ]  Follow-up
- [ ]  Filter
- [ ]  Export (simple/detailed/follow-up)
- [ ]  More
- [ ]  Import
## Events
- [x]  Create a new event
### Tab: Event
- [ ]  Event status
- [ ]  Date
- [ ]  Description
- [ ]  Source of information
- [ ]  Place
- [ ]  Create a new task
- [ ]  Create a new action
- [ ]  See cases for this event
- [ ]  See contacts for this event
### Tab: Event participant
- [ ]  Filter
- [ ]  Add person
    - [ ]  Involvement description
    - [ ]  Person Information
    - [ ]  Occupation & Education
    - [ ]  Place of residence
    - [ ]  Contact information
    - [ ]  Create a new sample
- [ ]  Create a case-ID (for existing participating persons)
- [ ]  Switch on bulk editing 
- [ ]  Create event actions
- [ ]  export (simple/detailed)
- [ ]  Bulk editing mode
- [ ]  Search
- [ ]  Set a filter
## Samples
- [ ]  Sample Directory (open existing sample)
### Tab: case, contact, event participant
- [x]  Create new sample
- [ ]  New test result
- [ ]  New test result (additional tests)
- [ ]  Export (simple/detailed)
- [ ]  Bulk editing mode
- [ ]  Set a filter
## User
- [ ]  Create a new user
- [ ]  Edit user
- [ ]  Create tasks for new user

**Comment by chThie** [comment]
@kavealimohammadi @JonasCir @eganov

**Comment by StefanKock** [comment]
This ticket is obsolete since the switch to another test framework. A similar list like here can be found in #5587.
