### ISSUE TITLE
API Automation Framework 

### ISSUE THREAD

**Issue by AndyBakcsy-she** [hzi-braunschweig/SORMAS-Project#5424]
### Task Scope
This ticket was created in order to have a starting point for the Automation work that will be done for the API part of Sormas
Other tickets should be created with more specific tasks related to this

### Proposed Plan

- [ ] Create a first draft of a simple Test Plan / Checklist of  what needs to be tested and what can be tested using the API
- [ ] Investigate and discuss with different developers any questions related to the API
- [ ] Start integrate a separate API automation into `sormas-e2e-tests` repo
- [ ] Address any concerns and get feedback/answers related to the API automation initiative.
- [ ] Log tickets if issues are found
- [ ] Use the  prioritized list received from HZI for the creation of a Sanity/Smoke Test suite 
- [ ] Investigate how the API automation Framework can be integrated with Jenkins and a reporting tool

### Additional Information
TBD

**Comment by alinapopaiustina** [comment]
[API automation strategy.docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/6501980/API.automation.strategy.docx)

**Comment by alinapopaiustina** [comment]
[API automation strategy.docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/6569702/API.automation.strategy.docx)
 Uploaded the review version of the document; note this is not the final version, but the one to be reviewed in the next checkpoint.

**Comment by alinapopaiustina** [comment]
[API automation strategy.docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/6602750/API.automation.strategy.docx)

**Comment by alinapopaiustina** [comment]
[API automation strategy.docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/6605836/API.automation.strategy.docx)
