### ISSUE TITLE
UI-Testing Automation Plan for next month

### ISSUE THREAD

**Issue by BojteTamas** [hzi-braunschweig/SORMAS-Project#5587]
# Tested Features

## Tasks

- [x]  Create a new task -> @BojteTamas ticket #5399 
- [x]  Edit created task -> @BojteTamas ticket #5404 

## Task Management

- [ ]  Basic export
- [ ]  Bulk editing mode
- [ ]  Filters
- [x]  Verify all fields on Task Management view -> @BojteTamas ticket #5665 

## Persons

- [x]  Edit person -> @rdutu-vg  ticket #5519 

## Cases

- [x]  Create a new case -> @BojteTamas
- [x]  Edit create case -> @BojteTamas ticket #5405
- [x]  Delete case -> @rdutu-vg ticket #5569 

### Tab: Case

- [x]  Create a new task
- [x]  Create a new sample
- [ ]  Link to an event    #5762
- [ ]  Create documents

### Tab: Hospitalization

- [x] Case Hospitalization tab -> @Mihai-Bota ticket #5615 

### Tab: Symptoms

- [x] Case Symptoms tab -> @BojteTamas ticket #5617 

### Tab: Epidemiological data

- [ ]  Exposure investigation  #5618 and #5663 
- [ ]  Activity as Case
- [ ]  Contacts with Source Case

### Tab: Follow-up

- [ ]  Export
- [x]  Create a new visit  -> #5749 

### Tab: Contacts

- [x]  Create a new contact -> @rdutu-vg ticket #5619
- [ ]  Set a filter
- [ ]  Switch on bulk editing
- [ ]  Import
- [ ]  Export

## Case Directory

- [ ]  Detailed view -> #5772  
- [x]  Follow-Up view -> #5773 
- [x]  Filter/Sort -> @VGitVlad  #5620 
- [ ]  Import (cases, case contacts)
- [ ]  Export (simple/detailed/etc.)
- [x]  Line listing - create cases  -> #5771 

## Contacts

- [x]  Create a new contact -> @rdutu-vg  ticket #5400 
- [x]  Edit create contact -> @Mihai-Bota #5406
- [x] Delete Contact -> @rdutu-vg ticket #5563 

### Tab: Contact

- [x]  Choose source case/ change case  -> @Mihai-Bota #5667 
- [ ]  Link event
- [ ]  Create a new task
- [ ]  Create a new sample
- [ ]  Create document

### Tab: Follow-up visits/calls

- [ ]  Export
- [ ]  Create a new visit/call  -> #5664 
- [ ]   Bulk editing mode

## Contacts Directory

- [x]  Detailed view -> @alinapopaiustina #5829 
- [ ]  Follow-up visits view -> covered as part of #5664
- [ ]  Export (simple/detailed/follow-up)
- [ ]  Set a filter
- [ ]  Import
- [ ]  Bulk edit mode
- [ ]  Merge duplicates
- [x]  Line listing - create contacts  -> #5835 

## Events

- [x]  Create a new event -> @richardbartha ticket #5401
- [x]  Edit event -> @richardbartha  ticket #5407 
- [x]  Actions View -> @alinapopaiustina #5837 
- [ ]  Groups View

### Tab: Event

- [x]  Create a new action -> @rdutu-vg  #5673 
- [x]  Create a new task -> @richardbartha ticket #5668 
- [ ]  Documents
- [ ]  Superordinate Event
- [ ]  Subordinate Events
- [x] Create event actions -> @rdutu-vg #5673 
- [x]  Add new group event -> @richardbartha #5690 
- [ ]  See cases for this event
- [ ]  See contacts for this event

### Tab: Event participant

- [x]  Add Event Participant -> @richardbartha ticket #5571 
- [ ]  Create a case-ID (for existing participating persons)
- [ ]  Switch on bulk editing
- [ ]  Export (basic/detailed/custom)
- [ ]  Import
- [ ]  Bulk editing mode
- [ ]  Set a filter

### Tab: Event actions

- [ ]  Set a filter
- [x]  Create an action -> @alinapopaiustina #5675 
- [ ]  Data Import (New Document)

## Samples

- [X]  Create new Sample -> @BojteTamas ticket #5402 
- [x]  Edit Sample -> @VGitVlad  ticket #5408 
- [x]  Delete Sample -> @rdutu-vg ticket #5745

### Tab: Sample

- [x]  New test result (pathogen tests) -> #5691 
- [ ]  New test result (additional tests)
- [ ]  Refer to another laboratory

## Sample Directory

- [ ]  Export (basic/detailed)
- [ ]  Bulk editing mode
- [x]  Verify all filters -> @VGitVlad  #5552 

## Lab Message Directory

- [ ]  Fetch lab messages
- [ ]  Enter bulk edit mode
- [ ]  Filters

## User

- [x]  Create a new user -> @horatiu-cosma  #5403 
- [x]  Edit user -> @horatiu-cosma  #5403 

## User Management

- [ ]  Export user roles
- [ ]  Enter bulk edit mode
- [ ]  Filters

**Comment by raghupola-vg** [comment]
[Automation initiative coverage.docx](https://github.com/hzi-braunschweig/SORMAS-Project/files/6736172/Automation.initiative.coverage.docx)
