### ISSUE TITLE
[S2S] Refactor and deduplicate S2S code

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Project#5599]
### Problem Description
While working on #5597, I noticed a lot of potential for code cleanup and deduplication which once resolved  would make my life easier. Also, I want to avoid merge hell along the way :imp: 

### Proposed Change
Not a complete list but:

- [x] `SormasToSormasEncryptionService` has code duplication and can be simplified for my work on #5597 (PR #5626  )
- [x] `SormasToSormasFacadeHelper` only encapsulates the sharing of data but not the receiving which causes a lot of code duplication in `AbstractSormasToSormasInterface` (PR #5672)
- [x] Reformat `MultiAuthenticationMechanism.java ` for smaller diff in concept PR
- [x] ~Private key does not have a dedicated password, but reuses password from keystore which is bad style~
- [x] Classes could be better organized PR up #5804
- [x] more to come...

**Comment by JonasCir** [comment]
All done

**Comment by JonasCir** [comment]
Nothing actionable for QA here, this was just a tracking issue.
