### ISSUE TITLE
Performance testing going forward

### ISSUE THREAD

**Issue by tamasvlad** [hzi-braunschweig/SORMAS-Project#5602]
- [x] [Dedicated repository for the performance scripts](https://github.com/hzi-braunschweig/SORMAS-Project/issues/5605)
- [x] [Create and configure CI pipeline for performance testing](https://github.com/hzi-braunschweig/SORMAS-Project/issues/5608)
- [x] [Calibrate the load for the CI performance testing execution](https://github.com/hzi-braunschweig/SORMAS-Project/issues/5611)
- [x] [Performance testing updates](https://github.com/hzi-braunschweig/SORMAS-Project/issues/5613)

**Comment by tamasvlad** [comment]
Proposed plan going fwd:
- install and configure application monitoring tools. Eg: New Relic - in order to monitor server resources during performance testing execution or investigate where the performance bottleneck is.
- the environment used for load testing should be similar to the production environment, otherwise the results are not relevant for production users.
- add more scripts covering different areas.
