### ISSUE TITLE
Populate the performance test system with at least 50 million persons

### ISSUE THREAD

**Issue by MateStrysewske** [hzi-braunschweig/SORMAS-Project#5986]
### Problem Description

In order to safely roll out the new features in #4081 and #5489, we need to make sure that they will not have a significant negative impact on the performance of the system, since using these features will bring a lot of data into the system. The two issues mentioned can't be released without some proper testing being done beforehand.

### Proposed Solution

Populate a performance testing environment with at least 50 million persons. Not all of them necessarily have to be associated with cases, contacts or event participants; half of them probably should.

### Additional Information

A PROD system already has 2mio cases, and the performance already is really (1.59).

#### Pre-requisites:
* #6266
* #6363
* #6362 (optional but low effort)
* #6364

#### Tasks for this issue

Run this against instance test-performance.sormas - it has the infrastructure entities for users, regions and districts that need to be used (known uuid).

- [x] Create Persons based on the pre-requisite scripts with one to five Immunizations (at least some random person names and sex, Person.additionalDetails = "created by API tests to create mass person data", one address and one phone number per person). No vaccinations needed to test this.
- [ ] Check how long injecting 100.000 entities takes. Check whether the bottle-neck is the test system or the system pushing the data or both. If it's the system sending the data, it might help to send from two or three systems at the same time.
- [ ] Scale up the available cores and RAM on the test system temporarily and check what effect it hat on creating another 100.000 entities. Experiment with this if possible
- [ ] Scale up the amount of persons to at least 1 mio and test the performance based on #6364
- [ ] Scale up the data more to up to 50mio persons to see where the system will not work with that amount of data anymore.
    
#### Follow-up
* Populate test system with cases
* Populate test system with contacts for that cases

@MartinWahnschaffe  discussed with @StefanKock

**Comment by bernardsilenou** [comment]
Can we also have results for 200 and 400 million persons? this falls in the lower bound for Nigeria

**Comment by JonasCir** [comment]
Point is you then need to directly insert this into the DB. Doing this via REST will take forever :D

**Comment by StefanKock** [comment]
As preprequisite for this ticket we should have running `e2e-performance-tests`.
- What endpoints to test with which role? 
- Do these endpoints already exist? If not they need to be implemented (maybe the methods that the `angular-app` will need in the future either way).
- Implement performance tests for the scenarios to keep tracked.

If the above prerequisite is fulfilled, we still need to define what data should be created and how to be injected. Judging the current `e2e-performance-tests` on contacts, injecting this amount of data would take about 72 days without parallel requests. One contact takes about 125ms to be pushed via REST-API.

**Comment by StefanKock** [comment]
I scheduled a refinement with @MateStrysewske and @rdutu-vg for next monday (2021-08-02).

**Comment by StefanKock** [comment]
Refinement for this ticket with @MateStrysewske and @AndyBakcsy-she:

> What endpoints to test with which role?

Test the following existing endpoints with several users with these roles: national user, surveillance officer and surveillance supervisor.
1. `PersonResource.getIndexList` (offset=0, size=100, criteria = null, sorting = null)
2. `PersonResource.getAllPersons` (since = long ago to get all)
3. `ImmunizationResource.getAllAfter` (since = long ago to get all)

> we still need to define what data should be created and how to be injected

- Create Persons with one to five Immunizations (at least some random person names, Person.additionalDetails = "created by API tests to create mass person data"). No vaccinations needed to test this.
- Inject the data with `e2e-tests` (API tests), scale up the amount of persons to at least 1 mio and test the performance.
- Scale up the data more to up to 50mio persons to see where the system will not work with that amount of data anymore.
- Run this against instance `test-performance.sormas`

Injecting via REST might take more time than directly per SQL, but we don't have a proper framework and approach to generate valid data with SQL. The REST approach can be automated and run for days if needed.

This ticket will be needed to be finished aside the immunizations feature in Sprint 107.

**Comment by rdutu-vg** [comment]
To save some time in the populating process, I have the next suggestion: 
Since all developers have the automation framework on local, we can trigger the test populating DB with persons via API calls using a script running in a loop. 
I'll do some tests soon as I'll have everything up and running, and check if this is a heavy resources consumer then I'll come back with the updates here if we'll take  in consideration this option.

**Comment by rdutu-vg** [comment]
Test script is done. 
We have a running test capable to generate 5 persons and 15 immunizations during an execution, which takes ~10s.
The test is designed to create a person first, then in 5 attempts, is attaching the immunizations in the following order:
Person 1 - 1 Immunizations
Person 2 - 2 Immunizations
Person 3 - 3 Immunizations
Person 4 - 4 Immunizations
Person 5 - 5 Immunizations

Allure execution:
![executionFromScript](https://user-images.githubusercontent.com/83643843/129758613-5d17addd-15e1-482e-8da4-aa6fbc223cac.PNG)

Local execution:
![executionFromLocal](https://user-images.githubusercontent.com/83643843/129758672-cca3d18a-7d0d-4325-9a5d-b1f7729b7e3a.PNG)

**Comment by rdutu-vg** [comment]
Updated test to assert also status code for post requests. Found something weird today, response body is ok but status code 204 and the immunizations are not created. I'll need to check.

https://github.com/hzi-braunschweig/SORMAS-Project/issues/6450

**Comment by rdutu-vg** [comment]
Performance endpoints were added, excepting getIndexList, getAllAfter. I will need more details to handle this.
I have updated some requests also with reponse asserts, they were missing, and I'm planning to do the same for all of them (will be covered in another ticket).
Right now there are some problems with the requests, all API POST tests are broken since 18 August, causing failures in performance tests and also in the script created to populate with Persons and Immunizations.

**Comment by rdutu-vg** [comment]
Test is fixed and stable 👍 
Triggered multiple executions in order to gather some data which can be found [HERE](https://github.com/hzi-braunschweig/SORMAS-Project/issues/6574)

@StefanKock  @MateStrysewske  how are we planning to start running the script? Can we create a jenkins job for it and trigger multiple executions?

**Comment by rdutu-vg** [comment]
Script was updated and seems to be stable.

I'll attach a baseline reference for performance results to compare once we'll have the data base populated with persons.

![baseline](https://user-images.githubusercontent.com/83643843/134018837-0d4b6a39-4afb-4069-841b-b903d09eaaa4.PNG)

**Comment by rdutu-vg** [comment]
Test performance started to be un-usable for automated tests. The get all persons call takes ~8min

https://jenkins.sormas.netzlink.com/view/SORMAS-Project/job/sormas-RunE2ePerformanceTests/247/performance/

**Comment by StefanKock** [comment]
Discuss in Sprint 109 what the current performance problems on test-performance are and how to solve them.

**Comment by StefanKock** [comment]
Closed as-is with the data we have
