### ISSUE TITLE
[SORMAS2SORMAS] Manage infrastructure data across all instances

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#6332]
### Situation Description

Sormas to Sormas communication requires a standard for infrastructure data because these are vital for coherent references across local instances. Since any local instance can include differing entries on any hierarchy level, it is difficult to provide a consistently functioning and coherent system if this condition is not met. To accomplish coherent data, an intermediate way to verify correct infrastructure data is needed.

As a Sormas Service Layer administrator, I would like to
- manage infrastructure data centrally and provide a standard against which shared data is verified.
- continuously make changes to these infrastructure data if necessary and inform S2S users about changes that have been made to the standard entries.

As a S2S user, I would like to 
- update my local infrastructure data according to changes made to the central standardized data set
- receive information about entries that do not fit the required standard
- adopt infrastructure data currently unknown to me (especially facilities) when receiving data by other S2S users

### Feature Description

- Allow depositing infrastructure data in the Sormas Service Layer - this data set represents the standardization
    - Follow the same data table structure as in Sormas
    - The standard would only account for continents, subcontinents, countries, regions, districts and communities
- Introduce a user interface (if needed) to manage the infrastructure data as a general administrator

### Scenarios

**Sharing**
- When a S2S user shares data with another instance, check the included infrastructure data against the standard and verify entries on the basis of the respective `externalId`
    - If the `externalId` of ALL the infrastructure data matches the standard exactly, share the data
    - If at least ONE `externalId` does not match, don't send ANY data and show the following error message to the user:

        _"The infrastructure data do not match the required format. Please review the following infrastructure data entries and adjust the external Id to match the required format"_

        - List all affected infrastructure data in the error message OR
        - provide an export/exports per table of the affected infrastructure data in a re-importable format - advantage: users can make all adjustments in the file and update their infrastructure data at once.

**Accepting**
- When a S2S user accepts shared data from another instance, check the included infrastructure data against the instances infrastructure data and verify entries on the basis of the respective `externalId`
    - If the `externalId` of ALL the infrastructure data matches the standard exactly, create shared data in the users instance and map infrastructure data according to the `externalId`
    - If at least ONE externalId does not match, don't create any data in the users instance and show them the following error message:

        _"The infrastructure data of the shared datasets include entries that do not match your instances infrastructure data. Please make sure that the following infrastructure data are included in your instance."_

        - List all affected infrastructure data in the error message OR
        - provide an export/exports per table of the affected infrastructure data in a re-importable format - advantage: users can make all adjustments in the file and update their infrastructure data at once.

### Crowdsourcing of facility data

Facilities can be very many and consistently changing. Thus, persistent standardization is almost impossible. To tackle this, crowdsourcing facility data might be a viable option and could work like this.

**Sharing**
- When a S2S user shares data with another instance, all included facilities are created in the Sormas Service Layer
    - If the facility has already been created once, it will not be created again to prevent duplicates. Duplicates are checked for via a unique constraint on the `externalId` and if it matches, Sormas Service Layer will accept this facility as one that it already knows and thus don't create it again
    - If facility information other than the `externalId` has changed, update the entry in the Sormas Server Layer

**Accepting**
- When a S2S user tries to accept data that has been shared by another instance, check the users instance for matching facilities on the basis of the `externalId`
    - If ALL facilities match (receiving instance knows all facilities), create the shared data in the users instance
    - If at least ONE facility does not match, show the user the following prompt in a pop-up:

    _"The shared data includes facilities that are unknown to your instance. You have the option to add shared facilities to your instance, proceed without adding the facilities or cancel the action."_

- Add buttons to the bottom of the pop-up: _CANCEL_, _VIEW UNKNOWN FACILITIES_, _ADD SOME FACILITIES AND ACCEPT_, _ADD ALL FACILITIES AND ACCEPT_
    - _CANCEL_: Cancel the whole acceptance action.
    - _VIEW UNKNOWN FACILITIES_: 
        - Open a form that looks like a replica of the facility creation window with viewing rights only.
        - Display each unknown facility in a respective form. 
        - Add arrows to flip through multiple unknown facilities (as seen for lab messages).
        - Add an option to close the window.
    - _ADD SOME FACILITIES AND ACCEPT_: 
        - Show the same facility form as above.
        - Add a checkbox to every individual form with the caption "Add facility to own instance".
        - If checked, add facilities to the users instance after accepting the share.
        - Map the unchecked facilities as OTHER_() for `facility` and the facility `name` to `facilityDetails`.
    - _ADD ALL FACILITIES AND ACCEPT_: Add all facilities to the users instance and create shared data.

- Conditions for facilities: facilities lie in standardized infrastructure data; other infrastructure data should ideally get validated beforehand 

### Additional Information

cf. https://github.com/hzi-braunschweig/SORMAS-Project/issues/5888 for potential duplicate handling

<img width="383" alt="infraDataShare" src="https://user-images.githubusercontent.com/70317594/128984780-1220fbf7-cd93-431b-b27b-cad8c57892d7.PNG">
<img width="262" alt="infraDataShare2" src="https://user-images.githubusercontent.com/70317594/128984782-5579dcb0-2edf-4c98-bbc0-3ea4998d515c.PNG">
<img width="301" alt="infraDataAccept" src="https://user-images.githubusercontent.com/70317594/128984783-fc2ac59a-e4d5-4cb0-af7f-371dd6ca9493.PNG">

Further things to think about:
- How to provide standardized data to users?
- How to handle hundreds of thousands of potential facilities?
- Option to Sync instances according to the service layer?

---

So here is @JonasCir 's plan
Phase 1
- [x] #6467
- [x] #6469
- [x] #6471
- [x] #6472
- [x] #6482

Phase 2
- [x] #6468
- [x] #6470
- [x] #6473

**Comment by kwa20** [comment]
@JonasCir @Candice-Louw @markusmann-vg Sorry for this issue having become this long but this is a first draft of how to potentially handle S2S centrally.

**Comment by JonasCir** [comment]
Here is what I propose:

### Centrally managed infrastructure data with central `etcd`

1. We provide serializable data for every subclass of `InfrastructureAdo` which includes everything from continent to community as JSON on the central `etcd`. 
2. Every time a case is shared with another peer, we check back with the central infra structure (alternatively central places the source of truth every 24 hours on the machines for faster lookup)
3. If infrastructure does not have the expected Name and external ID, we do not share and show an error advising the user to clean up the infrastructure data included in the case. 

### Changes in SORMAS

Mostly QOL changes:
1. Introduce a property to disable manually editing of infrastructure data. This is to make sure we do not have a moving target.
2. A user viewing a case containing e.g., an archived region has no indication about the fact the region was archived. Either show something like `My Region (archived)` as text or put a warning sign next to the box (@Candice-Louw what do you think is the best option is here?). The cleanup operation in the DB to be described in the next section will likely involve some archiving to resolve ID and name conflicts.

### DB cleanup and consistency for GAs
Provide SQL scripts to get the DB's mostly aligned to the central data set. We do not need to worry about all corner cases as we still do a sanity check before sending which means that in rare cases the user simply need to fix it manually.

We have the following cases to consider in the SQL script:

| local/central external ID | local/central name | Action |
| --- | --- |  --- |
| :heavy_check_mark: | :heavy_check_mark: | do nothing as row is correct | 
| :negative_squared_cross_mark: | :heavy_check_mark: |  If the local ID is _empty_ we can just insert the central external ID. Otherwise, this row needs to be archived and the correct entry needs to be inserted.|
| :negative_squared_cross_mark: | :negative_squared_cross_mark: | In this case we have rows that only exists on central or locally. The central ones can just be inserted. The local rows without a match are made up by the local GA, we cannot do anything automatically about them. If they try to send one case associated with them, the error will show and they need to figure it out. |

**Comment by kwa20** [comment]
@JonasCir A clash we need to think about: If the property to disable editing of infrastructure data is active, users will not be able to simply adjust their instances data.

**Comment by JonasCir** [comment]
They don't need to adjust instance data as the correct data will be provided from central to the local DB. 'Fixing' in this case means the user receives an error, go to the dropdown and selects a region that matches but was provided correctly.

**Comment by JonasCir** [comment]
So here is my plan (feel free to disagree):

- [ ] Store infrastructure data in central `etcd`
- [ ] Provide import/sync function from central to local DB
- [ ] Check outbound entities for correct infrastructure data
- [ ] Improve error message for infra. data mismatch
- [ ] Introduce a property to disable manually editing of infrastructure data
- [ ] A user viewing a case containing e.g., an archived region has no indication about the fact the region was archived
- [ ] Provide SQL scripts to get the DB's mostly aligned to the central data set

**Comment by JonasCir** [comment]
@markusmann-vg I think this can be moved to Released in the epic board :)
