### ISSUE TITLE
Refactor symptoms UI [3]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#664]
- [x] replace CaseDiseaseLayoutProcessor and Symptom class
- [x] symptoms read fragment: add "not set" symptoms tag list. "Not set" and "no" symptoms should be minimized by default
- [x] make sure all new fields are shown (see #631)
- [x] make sure all fields are shown based on the DiseaseConfiguration
- [x] make sure all dependencies to "parent" fields are correct (depends on #667)
- [x] ~~make sure validation is working correct~~ see #673
- [x] get rid of Symptoms.firstSymptom

**Comment by MartinWahnschaffeSymeda** [comment]
Fix symptoms read fragment:

- [ ] add missing monkeypox fields, especially lesions
- [ ] display "no symptoms" under symptom labels, when no symptoms is yes or unknown
- [ ] fields that are no "real" symptoms should not be display in tag view, but in read field. Add an "isSpecialSymptom" to SymptomsHelper
- [ ] make updateIsSymptomatic generic
