### ISSUE TITLE
Refactor epi data UI [2]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Project#668]
- [x] only show burials, gatherings, travels, when yes is checked
- [x] replace AnimalContact class and get rid of epid package
- [x] read fragment should not use tag fields
- [x] make sure all new fields are shown (see #632)
- [x] make sure all fields are shown based on the DiseaseConfiguration
- [x] make sure all dependencies to "parent" fields are correct (depends on #667)
- [x] burials edit & read
- [x] gatherings edit & read
- [x] travels edit & read
- [x] ~~make sure validation is working correct~~ see #673 

Wow.. Read layout just returns hardcoded entries - not the real data.

**Comment by MartinWahnschaffeSymeda** [comment]
@MateStrysewskeSym 
I'll take care of case epid layout (read & write)

**Comment by MartinWahnschaffeSymeda** [comment]
Additional tasks:

- [ ] LocationDialog field captions & layout
- [ ] Locaton dialog empties district and ward
