### ISSUE TITLE
Introduce new ticket type "epic"

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#7371]
### Problem Description
We are missing a consistent concept for "umbrella" tickets that that cover a large, complex and time taking topic.

### Proposed Solution

- [x] 1. Replace label `concept` with `epic` (conceptual work will be `task`s in the future if split out from refining the epic).
- [x] 2. Create a ticket template for epics.
- [x] 3. Add/align new labels for non-functional requirements: `data protection`, `accessibility`
- [x] 4. Set up a board to manage epics.
- [x] 5. Set up appropriate permissions (no team asssignment possible, only individuals assigned as editors).

**Comment by StefanKock** [comment]
I want to discuss the `epic` template.
