### ISSUE TITLE
Automatic deletion of personal data

### ISSUE THREAD

**Issue by StefanKock** [hzi-braunschweig/SORMAS-Project#7736]
### Situation Description & Motivation

Data collected for cases, contacts and the other core entities has to be deleted automatically after a given time period.

#### Use cases
- Travel entries have to be deleted 14 days after the date of arrival in country
- Data collected within a case has to be deleted depending on different regulations. Some fields are kept for 10 years, others for only 3 years after the end of processing.

### High-Level Explanation

We need to define and implement the automatic deletion of person-related data within SORMAS. 

- The deletion has to be done privacy-compliant - there is no way to undo the deletion. (at least after a given time period)
- The given time period for the deletion should be given in SORMAS and can be modifyed by the Gesundheitsamt.
- Deletion is happening 
- The Deletion concept can be found here (Important files: Main document; Annex 1(Anlage 01 - Löschregeln) ; Annex 4 (Anlage 04 - Umsetzungsvorgaben für einzelne IT-Systeme)): https://confluence.sormas-tools.de/pages/viewpage.action?pageId=14488475

### Timeline

TBD

#### Concept Phase

- [ ] Specification of deletion concept & implementation work

#### Implementation Phase 1

Automatic-soft deletion of entities.

- [ ] hzi-braunschweig/SORMAS-Project#7008
- [ ] hzi-braunschweig/SORMAS-Project#7240 
- [ ] hzi-braunschweig/SORMAS-Project#7246 
- [ ] hzi-braunschweig/SORMAS-Project#7247
- [ ] hzi-braunschweig/SORMAS-Project#7319    
- [ ] hzi-braunschweig/SORMAS-Project#7249

#### Implementation Phase 2

- [ ] hzi-braunschweig/SORMAS-Project/issues/7712
- [ ] hzi-braunschweig/SORMAS-Project/issues/7713
- [ ] hzi-braunschweig/SORMAS-Project/issues/7716
- [ ] Field-wise deletion in history data
- [ ] Import deletion config from Excel / data protection doc: https://github.com/hzi-braunschweig/SORMAS-Project/issues/6911
- [ ] Deletion of a record after transfer to another health authority -> 30 days!
- [ ] Automatic archiving for all entities

### Additional Information

One idea would be to use VACCUUM_FULL once per month.

**Comment by Marko-ilmkreis** [comment]
I would like to point out that the handling should be different upon the case classification. A "No Case" might be earlier deleted then a confirmed case.

For the travel entries please also include the contacts which are only a travel entry and not a contact to a case or converted into a case.

Please keep also contacts which results in a case anyway.

**Comment by MartinWahnschaffe** [comment]
@Marko-ilmkreis Thanks for the input on "no case".

Could you give some more details on the travel entries + contacts point, please?
Are you saying that you are creating a contact for a person that does have a travel entry, so the contact is created without an associated case and has the "returningTraveler" info set to true? 
Thus the contact would fall under the 14 day deletion period?

Would be good to have some details on this, so we can approach the data protection team.

**Comment by Marko-ilmkreis** [comment]
@MartinWahnschaffe Yes, as the import of the DEA travel entries is not really possible before 1.67 we use the contacts and set the returningTraveler to true. 
Thus contacts must fall under the deletion after 14 days if they are not also a contact to a case, a ep or if they are not converted into a case.
From 1.67 we hopefully will use the normal travel entries.

**Comment by MartinWahnschaffe** [comment]
Ok. I guess we will need to provide the means to manually delete those contacts in bulk, based on filters in the contact directory. The logic behind it will be a bit too specific to this workarround to extend the automatic deletion based on it.

**Comment by Marko-ilmkreis** [comment]
The filter for travel returns is still there, so a filter for "not resulting in a case" and "not an ep" is missing.

**Comment by MartinWahnschaffe** [comment]
I unfortunately didn't define a clear path on how to deal with campaigns. They are a core entity and can be manually deleted and as such they now also support automatic deletion, although this was not specified. In addition the permanent deletion of campaigns is not fully implemented, so it only works for campaigns that don't have campaign data yet.

There are now two ways forward:

1. Explicitly exclude campaigns form automatic and permanent deletion.
2. Extend the permanent deletion of campaigns to also include campaign data and extend the automatic deletion date checks to also include the dates of campaign data.

Solution 2 would be cleaner and more powerful, but comes with the drawback that deleting a whole campaign including all data may be a very big thing (comparable to deleting the aggregated reports of a whole country) that should not happen automatically.

Note: Campaigns are not used in Germany and thus aren't relevant for the related data security endeavor.

@Candice-Louw @Jan-Boehme Thoughts on this?

**Comment by MartinWahnschaffe** [comment]
@Candice-Louw Yes and no. The intention of campaigns is to capture aggregate data. 
Campaign forms have text fields, though, so we can't say for sure whether it is miss-used for collecting personal/sensitive data.

**Comment by SORMAS-JanBoehme** [comment]
@Candice-Louw @MartinWahnschaffe I also think that automatically deleting the whole campaign and relevant data for analytics and decision making just to be sure that no one has entered personal / sensitive data in any text fields is a bit much.

The middle ground in my opinion would be to exclude campaigns that have data associated with them from the automatic deletion and add the standard mouse over info to text fields in which the users are informed about the GDPR agreement and that they must not enter any sensitive data in these fields like we have it in other forms
