### ISSUE TITLE
Enable SORMAS to deal with the DEMIS physician's reports profiles

### ISSUE THREAD

**Issue by FredrikSchaeferVitagroup** [hzi-braunschweig/SORMAS-Project#8268]
### Situation Description & Motivation

The RKI built this [new set of DEMIS profiles](https://simplifier.net/DEMISArztmeldung/) allowing hospitals (and later also others, e.g. registered dorctors (niedergelassene Ärzte)) to report hospitalizations of cases.

The current plan of RKI is to rollout those profiles to production on March 16th.

As those profiles are also going to be used for COVID-19, notifications using those profiles will also be transmitted to SORMAS, where it has to be dealt with them.

### High-Level Explanation

Due to the very limited time left before the rollout, there probably will be two phases. One first phase to quickly apply changes via hotfixes to accomodate some very basic functionalities regarding the new profiles. Then another longer phase to implement real mapping, structuring and processing. This epic is about the first phase. The second one is dealt with in #6430.

### Tasks

Tickets concerning very basic functionalities (1st phase):
- [x] [#53](https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/53)
- [ ] ~~[#54](https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/54)~~
- [x] [#56](https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/56)
- [x] #8276

Tickets regarding the more avanced changes (2nd phase):

(see #6430)

### Risks

Currently, there seems to be a balance necessary between two risky behaviours:
1. Making changes too slow or too little to allow users to deal with those new profiles directly after rollout.
2. Quickly implement poorly planned changes that lead to broken database states or otherwise unusable production instances.

**Comment by kwa20** [comment]
@FredrikSchaeferVitagroup Since https://github.com/hzi-braunschweig/sormas-demis-adapter/issues/54 was discarded, can we close this epic?

**Comment by FredrikSchaeferVitagroup** [comment]
Yes, wen can. Thank you for pointing this out.
