### ISSUE TITLE
User role administration concept [3]

### ISSUE THREAD

**Issue by MartinWahnschaffe** [hzi-braunschweig/SORMAS-Project#898]
Based on #830.

General idea is to get rid of fixed user roles and replace them with user rights only that can be combined in a configurable user role.
The default user roles would be based on the existing SORMAS user roles.

- [x] create a concept for this (mockup + data schema)
- [x] discuss with RKI

Consider:

* define if user role has access to web and/or app
* limit the available user rights for each role based on availability for web and app. E.g. deletion, import, export, archive, etc. are only available for the web app
* add user interface to edit assigment of user rights to user roles
* display default configuration in hover info
* find a proper name for user right and user behaviours/assignments
* maybe use user right groups / user feature to have something between the general persons and the granular user rights (e.g. case investigation). At least in the UI

Result summary: https://github.com/hzi-braunschweig/SORMAS-Project/issues/898#issuecomment-671336289

**Comment by MartinWahnschaffeSymeda** [comment]
This also needs to be done (-> more effort):

- [ ] define if user role has access to web and/or app
- [ ] limit the available user rights for each role based on availability for web and app. E.g. deletion, import, export, archive, etc. are only available for the web app
- [ ] make sure all app user rights are fully implemented

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda 
We need to expand the report module or aggregate linelist module to be able to categorize cases reported by user roles. This exists in the case directory with a filter called "Reported by" However, when you export it, you dont have any access to the reporting user ids or the user roles themselves. On PgAdmin its possible to export the case table and have the reportinguser_id but we need to be able to always filter by user role then by reporting user id in the exported case tables. It is not easy goign through each reporting user id by district id or region id with over 20000 cases

Also we need to add number of cases created by user role in the report section in SORMAS or expand the aggregate linelist to have such a report. THis is to enable users measure performance of field officers based on data entered by them (completeness, usefulness, data quality). 

We can discuss this further tommorow. 

A bug maybe- The filter by "reported by" does not seem to filter correctly> I can reporduce this for you tommorow.

**Comment by bernardsilenou** [comment]
@MartinWahnschaffeSymeda : With respect to your point 2 (limit the available user rights for each role based on availability for web and app. E.g. deletion, import, export, archive, etc. are only available for the web app), What is the challenge if we do not limit the user roles. What I mean is that the a user with the rights of the current informant/ SO will be able to use the web application also. Every role (which will  be a combination of cert in rights) will be able to use the web. In addition to this, certain roles, like informant will have the additional option to use the mobile version or SORMAS.

**Comment by MateStrysewskeSym** [comment]
Additional questions:

- [ ] How do we migrate from the current model to the new model on the existing systems?

**Comment by MateStrysewskeSym** [comment]
Current concept: Store a UserRole entity in the database that has a "name" column, a "default" column (boolean, true if it's a default SORMAS user role; default roles should not be deletable from the UI) and a "userrights" column which contains a JSON or JSONB string with the names of all user rights that are enabled for this user role.

**Comment by MateStrysewskeSym** [comment]
Current user role combinations in the Nigerian system:

* Admin & National User: 13
* Surveillance Supervisor & Case Supervisor: 13
* Surveillance Supervisor & Contact Supervisor: 9
* National User & National Clinician: 4

Further combinations that are only set for one user:
* Surveillance Supervisor & Event Officer
* National User, Surveillance Supervisor & Event Officer
* Surveillance Supervisor, Contact Supervisor & Event Officer
* National Observer & Contact Supervisor
* Contact Supervisor & Event Officer
* Surveillance Officer & Contact Officer
* National User, Case Supervisor & Contact Supervisor
* National User, Surveillance Supervisor & Contact Supervisor
* National User & Lab User

**Comment by MateStrysewskeSym** [comment]
New mockups:
https://app.moqups.com/3NUENEwuOE/view/page/ab4eb9432
https://app.moqups.com/3NUENEwuOE/view/page/ad7b3a18e

**Comment by MateStrysewskeSym** [comment]
Additional request from Ghana: We should probably make sure that the "Admin" role is not deletable and that there is a specific user right that allows/prevents the creation of "Admin" users (see #1475)

**Comment by MartinWahnschaffeSymeda** [comment]
Refinement:

- [ ] remove "create" user rights - "edit" is sufficient
- [ ] combine view/edit and list the related entities/entity parts

**Comment by markusmann-vg** [comment]
Considering the jurisdiction part when implementing the story

**Comment by MartinWahnschaffeSymeda** [comment]
I have updated the mockups for the edit form: https://app.moqups.com/3NUENEwuOE/view/page/a46f29001

What still needs to be done:

- [ ] Update the mockup for the list view
- [ ] Define how the current user roles & rights combination can be exported -> should be similar to the existing user rights Excel table

User rights that need to be refined:

- [ ] National User: SAMPLE_DELETE without SAMPLE_EDIT_NOT_OWNED does not make sense -> DELETE should include it
- [ ] CASE_MANAGEMENT_ACCESS vs. THERAPY_VIEW + CLINICAL_COURSE_VIEW
- [ ] Case Management user rights are confusing
- [ ] DASHBOARD_VIEW vs. DASHBOARD_SURVEILLANCE_ACCESS vs. DASHBOARD_CONTACT_ACCESS
- [ ] USER_RIGHTS_MANAGE?
- [ ] CONFIGURATION_ACCESS?

Additional refactorings needed:

- [ ] Replace all direct usages of user roles either with a user right or with a "property" in the new user role class (similar to the jurisdiction)
- [ ] Remove no longer needed convenience methods like AbstractAdoService.isAdmin, hasUserRole

**Comment by StefanKock** [comment]
Temporarly moved the ticket out of Done column to archive tickets of Sprint 100

**Comment by StefanKock** [comment]
With redefining this as `epic`, it is considered to still be open.

**Comment by MartinWahnschaffe** [comment]
> I am hoping that we are adding a Mobile app login ability as well in this user management thing.

What do you mean by login ability? A user right that allows/forbids users to use the mobile app?

**Comment by kwa20** [comment]
> Add short documentation for this: https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/docs/SERVER_CUSTOMIZATION.md#user-role-configuration

A wiki entry for userrole configuration shoud be added as well

**Comment by abrudanancuta** [comment]
The new discovered scenarios while doing exploratory testing on User Right & Roles:

Bugs and changes

- https://github.com/hzi-braunschweig/SORMAS-Project/issues/10094
- https://github.com/hzi-braunschweig/SORMAS-Project/issues/10034
- https://github.com/hzi-braunschweig/SORMAS-Project/issues/10033
- https://github.com/hzi-braunschweig/SORMAS-Project/issues/10190
- https://github.com/hzi-braunschweig/SORMAS-Project/issues/10189
- https://github.com/hzi-braunschweig/SORMAS-Project/issues/10192
- https://github.com/hzi-braunschweig/SORMAS-Project/issues/10188

**Comment by roxanamlendea** [comment]
The bug reports added by me while doing exploratory testing on User Roles and Rights:
- #10188 
- #10192

**Comment by roxanamlendea** [comment]
Other issues related to User Rights and Roles:
- #10341
- #10426 
-

**Comment by adinaflorea9** [comment]
Other issues related to User Roles and Rights:

- #10474 
- #10190 
- #10189 
- #10564

**Comment by adinaflorea9** [comment]
Other issues related to User Roles and Rights:
- #11330
